import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TanstackClientProvider from "../contexts/TanstackClientProvider";
import { AuthConetxtProvider } from "../contexts/AuthContext";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-teal-600`}
      >
          <TanstackClientProvider>
            <AuthConetxtProvider>{children}</AuthConetxtProvider>
          </TanstackClientProvider>
        <Toaster/>
      </body>
    </html>
  );
}
